### ISSUE TITLE
Update tensorflow to 2.0 and keras to 2.2.5

### ISSUE THREAD

**Issue by nagdevAmruthnath** [rocker-org/ml#27]
### Not an Issue
**Just a comment/Request**
Tensorflow 2.0 and keras 2.2.5 has been released for a while. Is there a plan to update the versions? It seems fairly simple to update on dockerfile.

**Comment by cboettig** [comment]
@nagdevAmruthnath excellent question!    I've just tickled the build again on the experimental tag on `rocker/ml:cuda-10.0`,  which I think should now be pulling in tensorflow 2.0.    

However, note that it's not really a question about "simply updating the dockerfile" -- last I checked, over 70% of the examples in https://keras.rstudio.com/articles/examples/index.html included keras code that was not ported over to Tensorflow 2.0 and would no longer run (particularly on the GPU side **EDIT** *Most of these issues are due to going to CUDA 10.0 rather than just Tensorflow 2.0*).  That was a few months ago, so many of those issues may now be resolved, and at least some of those errors may not have been directly related to 2.0 issues.  We'd certainly welcome comments and feedback on compatibilities.

We're still working out the best model to use for building and tagging images that will preserve functionality across the triangulation of Tensorflow versions, R versions, and cuda versions.  Thoughts on how to do that are very welcome!

**Comment by nagdevAmruthnath** [comment]
Hi Carl. Thanks for the update. I did a quick read about it and see that there is also compatibility issues with cuda versions `cuda-10.0` and `cuda-10.1` for `tensorflow==2.0` . Currently there is no stable version for `tensorflow==2.0`. There is 2.0a0 2.0e0. I tried to upgrade them and run R library, apparently R looks for `2.0` and not `2.0a0`  which leads to an error. I guess we might as well wait for tensorflow team to release stable version.

**Comment by cboettig** [comment]
@nagdevAmruthnath thanks for the follow-up! Yup, it's still the wild west on the `ml` stack I think.  You can get R talking to the 2.0 tensorflow but takes some wrangling (the `greta` devs have moved to 2.0 already I believe). We're hoping to hammer out a more deliberate approach  to get stable combinations that can still keep pace as close to the cutting edge as we can manage.  Watch this space and we should have more news on that front

**Comment by nagdevAmruthnath** [comment]
@cboettig Thanks! I will keep an eye out on it.

**Comment by eddelbuettel** [comment]
I lurk over at the reticulate and tensorflow repos and there are still lots of changes.  I don't follow _that_ closely though.   Also good to know that 2.0 already works for greta.
